.TH PYTRAINER 1
.SH NAME
pytrainer - sport activity logging tool

.SH SYNOPSIS
pytrainer [options]

.SH DESCRIPTION
pytrainer is a desktop application for logging and graphing sporting activities such as running or cycling sessions. Data can be imported from GPS devices, files or input manually. Currently pytrainer supports GPX, TCX, and FIT files.

.SH OPTIONS 
.IP "-h, --help"
show this help message and exit
.IP "-d, --debug"
enable logging at debug level
.IP "-i, --info"
enable logging at info level
.IP "-w, --warn"
enable logging at warning level
.IP --valid
enable validation of files imported by plugins (details at info or debug logging level) - note plugin must support validation
.IP --oldgraph 
Turn off new graphing approach
.IP --newgraph
Deprecated option: turn on new graphing approach
.IP --confdir=CONF_DIR  
Specify the directory where application configuration will be stored.
.IP --logtype=TYPE
Specify where logging should be output to. TYPE is one of 'file' (default), or 'console'.

.SH EXAMPLES
.IP pytrainer
starts pytrainer with log level set to ERROR
.IP "pytrainer -d"
starts pytrainer with log level set to DEBUG (troubleshooting)

.SH AUTHORS
This manual page was originally written by Braulio Valdivielso <brlvldvlsmrtnz@gmail.com> and polished by Christian Perrier <bubulle@debian.org>. Detailed information and further changes by David García Granda <dgranda@gmail.com>.
.P
For more information please check 'Credits' in 'About' menu.
.P
Thanks to everyone who contributes and supports pytrainer.

.SH SEE ALSO
Project web site: https://github.com/pytrainer/pytrainer
.br
Distribution list: pytrainer-devel@lists.sourceforge.net
