a.u=0;a.H=1;a.G=2;a.I=3;a.d=0;a.c=1;a.e=2;a.f=3;a.z=navigator.userAgent;a.t=typeof opera!="undefined";a.s=!a.t&&a.z.indexOf("MSIE")!=-1;a.F=!a.t&&a.z.indexOf("Safari")!=-1;a.w="curve";a.m="rc_bg";a.v="rc_border";a.SIGMOID_FUNCTION_WIDTH=12;a.SIGMOID_FUNCTION_OFFSET=6;function a(){}a.prototype.j=function(b){return b};a.prototype.k=function(b){return b+1};a.prototype.i=function(b){return b};a.prototype.l=function(b){return b+1};a.prototype.h=function(b,e,c){b=12*b/e-6;return c/(1+Math.exp(b))};a.prototype.o=
function(b,e,c){if(b<=0)return e;if(b>=c)return 0;b=b/c;var d=Math.log((1-b)/b);return e*(d+6)/12};a.prototype.b=function(b,e){var c=Math.sqrt(Math.pow(e,2)-Math.pow(b,2));return isNaN(c)?0:c};a.prototype.g=function(b,e){if(a.s){document.styleSheets[0].addRule(b,e)}else{var c=document.createElement("style");c.type="text/css";var d=a.F?"innerText":"innerHTML";c[d]=b+"{"+e+"}";var f=document.getElementsByTagName("head")[0];f.appendChild(c)}};a.prototype.a=function(b,e,c,d,f){var g=document.createElement("div"),
h="position:absolute;overflow:hidden;left:";h+=b;h+="px;top:";h+=e;h+="px;width:";h+=c;h+="px;height:";h+=d;h+="px;";if(f!=null){h+="opacity:";h+=f;if(a.s){h+=";filter: alpha(opacity=";h+=Math.round(f*100);h+=");"}}g.style.cssText=h;return g};a.prototype.B=function(b,e,c){var d=new Array(4);d[a.e]=this.b(this.j(b),c);d[a.f]=this.b(this.k(b),c);d[a.c]=this.b(this.i(e),c);d[a.d]=this.b(this.l(e),c);return d};a.prototype.D=function(b,e,c,d){var f=new Array(4);f[a.e]=this.h(this.j(b),c,d);f[a.f]=this.h(this.k(b),
c,d);f[a.c]=this.o(this.i(e),c,d);f[a.d]=this.o(this.l(e),c,d);return f};a.prototype.C=function(b,e,c,d){var f=this.D(b,e,c,d),g=this.q(b,e,f);return g==-1?0:g};a.prototype.r=function(b,e,c,d){var f=this.B(b,e,c),g=this.q(b,e,f);if(g==-1){return 0}return d?1-g:g};a.prototype.q=function(b,e,c){var d=0,f=new Array(2),g=new Array(2),h=false,o=false,k=false,j=false,i=this.i(e),p=this.l(e),n=this.j(b),s=this.k(b);if(c[a.e]>=i&&c[a.e]<p){h=true;f[0]=0;g[0]=c[a.e]-i}else if(c[a.d]>=n&&c[a.d]<s){o=true;f[0]=
c[a.d]-n;g[0]=1}if(!o&&!h){return-1}if(c[a.f]>=i&&c[a.f]<p){k=true;f[1]=1;g[1]=c[a.f]-i}else if(c[a.c]>=n&&c[a.c]<s){j=true;f[1]=c[a.c]-n;g[1]=0}if(h&&k){var m=g[0]<=g[1]?g[0]:g[1],l=g[0]>g[1]?g[0]:g[1];d=m+(l-m)/2}else if(h&&j){d=g[0]*f[1]/2}else if(o&&k){d=1-(1-f[0])*(1-g[1])/2}else if(o&&j){var q=f[0]<=f[1]?f[0]:f[1],t=f[0]>f[1]?f[0]:f[1];d=q+(t-q)/2}return d};a.prototype.p=function(b,e,c,d,f,g){this.g("#"+b.id+" ."+a.w+" div","background-color: "+d);b.style.display="none";var h=this.a(0,0,e,c);
h.className=a.w;var o,k=c-1,j,i,p,n,s=c-1;for(var m=0;m<e;++m){o=k;k=Math.floor(this.h(m+1,e,c));i=f?m:e-m;p=g?0:c-k;j=this.a(i,p,1,k);h.appendChild(j);for(var l=k;l<=o;++l){n=this.C(m,l,e,c);p=g?l:s-l;j=this.a(i,p,1,1,n);h.appendChild(j)}}b.appendChild(h);b.style.display=""};a.prototype.n=function(b,e,c,d,f,g,h,o){this.g("#"+b.id+" ."+a.m+" div","background-color: "+d);this.g("#"+b.id+" ."+a.v+" div","background-color: "+f);e+=g;c+=g;var k=b.style;k.display="none";b.innerHTML="";k.position="absolute";
k.borderWidth="0px";k.backgroundColor="transparent";var j=g+"px solid "+f,i=o==a.u||o==a.G,p=o==a.u||o==a.H,n=e-h;if(n>0){var s=i?e-n:0,m=this.a(s,0,n,c-g),l=m.style;l.backgroundColor=d;p?(l.borderTop=j):(l.borderBottom=j);b.appendChild(m)}var q=c-h;if(q>0){var t=p?c-q:0,m=this.a(0,t,e-g,q),l=m.style;l.backgroundColor=d;i?(l.borderLeft=j):(l.borderRight=j);b.appendChild(m)}this.A(b,e,c,h,g,i,p);k.display=""};a.prototype.A=function(b,e,c,d,f,g,h){var o=f>0,k=d-f,j=g?0:e-d,i=h?0:c-d,p=this.a(j,i,d,
d);p.className=a.m;var n=this.a(j,i,d,d);n.className=o?a.v:a.m;var s=k,m=d,l=k,q=d,t,w,x,u,y=d-1;for(var v=0;v<d;++v){j=g?y-v:v;s=l;m=q;l=Math.ceil(this.b(v+1,k));q=Math.floor(this.b(v+1,d));t=o?s:q;i=h?d-t:0;u=this.a(j,i,1,t);p.appendChild(u);for(var r=q;r<=m;++r){x=this.r(v,r,d,false);i=h?y-r:r;u=this.a(j,i,1,1,x);n.appendChild(u)}if(o){w=q-t;if(w>0){i=h?d-t-w:t;u=this.a(j,i,1,w);n.appendChild(u)}for(var r=l-1;r<s;++r){x=this.r(v,r,k,true);i=h?y-r:r;u=this.a(j,i,1,1,x);n.appendChild(u)}}}b.appendChild(p);
b.appendChild(n)};window["$"]=function(b){return document.getElementById(b)};a.prototype["csc"]=a.prototype.p;a.prototype["arc"]=a.prototype.n;window["asg"]=new a;
